import '../lib/orpc.server';
import '../lib/polyfills';
import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import { SiteHeader } from "@/components/home/SiteHeader";
import { SiteFooter } from "@/components/home/SiteFooter";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import QueryProvider from '@/lib/react-query';
import NextTopLoader from 'nextjs-toploader';
import { Toaster } from "@/components/ui/sonner"
const beVietnamPro = Be_Vietnam_Pro({
    weight: ["300", "400", "500", "600", "700", "800"],
    subsets: ["latin"],
    variable: "--font-geist-vietnam",
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth.api.getSession({
        headers: await headers()
    })
    return (
        <html lang="en">
            <body
                className={`${beVietnamPro.variable}  antialiased`}
            >
                <QueryProvider>
                <NextTopLoader color="#EC2229" height={3} showSpinner={false} />
                   {children}
                    <Toaster position='bottom-right' />
                </QueryProvider>
            </body>
        </html>
    );
}
